version: "3.9"
networks:
    fullstack:
      driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    networks:
      - fullstack
    depends_on:
      - postgres
    env_file:
      - .env.example
    ports:
      - '8082:8082'
  test:
    build:
      context: .
      dockerfile: Dockerfile
    image: app:test
    command: ["go", "test", "-v", "./api/controllers", "./api/services", "./api/repositories"]


  postgres:
    image: postgres:14-alpine
    container_name: "db"
    ports:
      - "8085:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database_dockerizing:/var/lib/postgresql/data
      - ./dbshell:/docker-entrypoint-initdb.d/
    networks:
      - fullstack

volumes:
    database_dockerizing:
    api_volume:
